### ISSUE TITLE
ImportError: cannot import name Feature

### ISSUE THREAD

**Issue by Dillonsmart** [fireeye/PwnAuth#10]
When running setup.sh with the current version of the app I got the following error: 
```
from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
```
To fix this issue I had to update MarkupSafe in app/requirements.txt to 1.1.1. There is a bug with Markupsafe 1.0.

**Comment by dmb2168** [comment]
This has been fixed thanks for the note and sorry it took me so long to get to it in master
